---
title: ""
---

## Summary

**Computational Biologist** with a focus on gene expression and sequencing-based screen analyses. Expert in single-cell transcriptomics, epigenetics, genome annotation, large-scale pooled and arrayed screens. Academic, biomedical, and industry background, including team and project management.

## Experience

**Senior Computational Biologist** in the Next Generation Sequencing and Datapoints Teams, Ginkgo Bioworks, Boston, MA, USA (April 2022 - Present)

- Led analyses and developed bioinformatics workflows for sequencing-based single-cell and arrayed genetic screens (Perturb-Seq and DRUG-seq), significantly improving our functional genomics capabilities
- Established single-cell/nucleus RNA-seq approaches to optimize AAV vectors for gene therapy, enabling the identification of crucial factors affecting packaging yield and tissue-specificity 
- Developed methodologies for high-throughput screening of sequence elements influencing mRNA and circular RNA vectors efficacy using polysome profiling data 
- Implemented standardized workflows for in-house genome annotation, enhancing consistency and reproducibility across projects

**Single-Cell Genomics Team Lead** in the Center for Cancer Genomics, Dana-Farber Cancer Institute, Boston, MA, USA (May 2018 - March 2022)

-   Led team with a focus on molecular profiling of the tumor micro-environment using single-cell RNA and ATAC sequencing
-   Developed workflows from clinical sample collection to sequencing data analysis
-   Contributed to more than 30 clinical studies and atlases, including large consortia such as the Human Tumor Atlas Network

**Research Scientist** in the Gimelbrant Lab, Dana-Farber Cancer Institute, Boston, MA, USA (July 2013 - May 2018)

-   Investigated the mechanisms and function of genome-wide monoallelic gene expression
-   Developed a machine-learning tool set and web application to infer monoallelic expression from chromatin marks
-   Conducted sequencing-based shRNA and drug screening to identify factors controlling allelic expression
-   Implemented an inDrop single-cell RNA sequencing platform

**Research Fellow** in the Bartolomei Lab, University of Pennsylvania School of Medicine, Philadelphia, PA, USA (March 2008 - June 2013)

-   Investigated genetic and epigenetic controls of cell-type specific gene expression
-   Characterized functionally distinct classes of binding sites for the transcriptional regulator protein CTCF
-   Developed a cell model for the high-throughput screening of factors capable of reverting Rett syndrome
-   Awards: Post-doctoral fellowships from the French Foundation for Medical Research and the American Heart Association

**PhD Candidate** in the Avner Lab, Pasteur Institute, Paris, France (September 2003 - September 2007)

-   Investigated genetic and epigenetic factors controlling X chromosome inactivation
-   Identified genomic elements controlling X chromosome inactivation using targeted deletions in mouse
-   Award: Doctoral fellowship from the French Association for Research against Cancer

## Education

**PhD in Development Biology** from Pierre and Marie Curie University, Paris, France (October 2003 - September 2007)

**Master in Molecular, Cell, and Developmental Biology** from Pierre and Marie Curie University, Paris, France (September 2002 - July 2003)

**Bachelor in Cell Biology** from Paul Sabatier University, Paris, France (September 1998 - July 2002)

## Technical Skills

**Programming:** Bash, R, Python, Perl, Awk, SQL, Git, Docker, Snakemake, Nextflow

**Computational Biology:** Bulk and single-cell transcriptomics and epigenomics data analysis, sequencing-based arrayed and pooled screen analysis, genome annotation

**Experimental Biology:** Transcriptomics, epigenomics, molecular biology, mouse embryology, cell biology, microscopy

**Management:** Team hiring and training, lab and project management, data and metadata collection and sharing

## Other Experiences

**Instructor and Editor** with Software Carpentry, online and in Boston, MA, USA (2018 - Present)

**Learning Circle Facilitator** with Peer 2 Peer University and BosLab, online and in Boston, MA, USA (2018 - 2021)

**Course Developer** with the University of the People, online (2015)

**Teaching Assistant** with the University of Pennsylvania School of Science, Philadelphia, PA, USA (2012)

**Science Project Mentor** with iPraxis, Philadelphia, PA, USA (2008-2010)

## Publications

[Pubmed](https://pubmed.ncbi.nlm.nih.gov/?term=sebastien+vigneau&ac=yes&cauthor_id=None&user_filter=&schema=none&page=1&whatsnew=None&show_snippets=on&sort=date&sort_order=desc&format=summary&size=10)

[protocols.io](https://www.protocols.io/researchers/sbastien-vigneau1/publications)
